# What is Pytorch

### PyTorch is an open source machine learning and deep learning framework.

In [1]:
import torch
torch.__version__

'1.7.1'

## Creating Tensors

In [2]:
# Scaler
scaler = torch.tensor(10)
scaler

tensor(10)

In [3]:
# Dimesion of Tensor
scaler.ndim

0

In [4]:
#Get Item
scaler.item()

10

#### Now its time for Vectors

In [5]:
# Creating a vector
vector = torch.tensor([10,5])
vector

tensor([10,  5])

In [6]:
# Vector Dimension
vector.ndim

1

In [7]:
# Shape of vector
vector.shape

torch.Size([2])

#### Let's look some matrices in torch

In [8]:
mat = torch.tensor([[1,2],
                   [3,4]])
mat

tensor([[1, 2],
        [3, 4]])

In [9]:
# dim of matrix

In [10]:
mat.ndim

2

In [11]:
# Shape of matrix
mat.shape

torch.Size([2, 2])

#### Tenors

In [12]:
tensor = torch.tensor([[[1,2,3],
                       [4,5,6],
                       [7,8,9]]])

tensor

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [13]:
tensor.ndim

3

In [14]:
tensor.shape

torch.Size([1, 3, 3])

#### Create Random value Tensor

In [15]:
rand_tensor = torch.rand(size=(3,3))
rand_tensor

tensor([[0.9733, 0.7423, 0.0980],
        [0.5298, 0.7347, 0.0662],
        [0.9790, 0.1250, 0.6381]])

In [16]:
# create an random  value image

img_rand = torch.rand(size=(240,240,3))
img_rand.shape

torch.Size([240, 240, 3])

#### Creating Ones and Zeros Tensor

In [17]:
zeros = torch.zeros(size=(4,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [18]:
ones = torch.ones(size=(4,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

### Creating Range Like Tensor

torch.arange(start,end,step)

In [19]:
torch.arange(start=10,end=40,step=2)

tensor([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38])

In [20]:
# Create float type tensors

torch.tensor([1.5,6.7,8.0],dtype=torch.float16)

tensor([1.5000, 6.6992, 8.0000], dtype=torch.float16)

### Information about Tensors

shape - what shape is the tensor? (some operations require specific shape rules)

dtype - what datatype are the elements within the tensor stored in?

device - what device is the tensor stored on? (usually GPU or CPU)

In [21]:
mat = torch.tensor([1,2,3])

print(mat.shape)
print(mat.dtype)
print(mat.device)

torch.Size([3])
torch.int64
cpu


## Tensor Operation

In [22]:
# Create a tensor 
tensor =  torch.tensor([2,4,6])

In [23]:
# Addition
tensor + 5

tensor([ 7,  9, 11])

In [24]:
# Substract

tensor-2

tensor([0, 2, 4])

In [25]:
# Multiply

tensor *10

tensor([20, 40, 60])

In [26]:
# Operation + Reasign

tensor = tensor + 10
tensor

tensor([12, 14, 16])

In [27]:
# torch function for multiplication

torch.multiply(tensor,2)

tensor([24, 28, 32])

In [28]:
# Element wise multiplication

mat1 = torch.tensor([1,2,3])
mat2 = torch.tensor([2,3,4])

mat1 * mat2

tensor([ 2,  6, 12])

In [29]:
# Mat mul

torch.matmul(mat1,mat2)

tensor(20)

In [30]:
# Can also use the "@" symbol for matrix multiplication, though not recommended
mat1 @ mat2

tensor(20)

In [31]:
a1 = torch.tensor([[2,3],[4,5]])
a2 = torch.tensor([[5,6],[7,8]])

torch.matmul(a1,a2)

tensor([[31, 36],
        [55, 64]])

### We can also use nn module from torch for mat multiplication

From an neural network perspective

### y= x⋅A_T+ b

x: input

A_T: weights 
(Remember that we will take transpose of weights matrix if we don't do it nn module throws shpae mismatch error)


b: bias

y: output

In [32]:
x = torch.rand(size=(2,3))
x

tensor([[0.9084, 0.4765, 0.8041],
        [0.5975, 0.9075, 0.0907]])

In [33]:
x.ndim

2

In [34]:
# in_feature: matches inner dimension of inputs
# out_features: describes outer values

linear = torch.nn.Linear(in_features=3,out_features=4)

In [35]:
linear(x)

tensor([[-0.9178,  0.1314,  0.0140, -0.2461],
        [-0.4482,  0.4866,  0.0928, -0.1793]], grad_fn=<AddmmBackward>)

Ok let's see what is happening in this module

in_features specify the inner dimension of the matrix means actually the no of column of the matrix

out_features: the output is for desired output shape (From deep learning perspective we can say it as output neuron)

#### Agregation Operations

In [36]:
tensor =  torch.rand(size=(10,))
tensor

tensor([0.1908, 0.8334, 0.8143, 0.9610, 0.6294, 0.3123, 0.7598, 0.3975, 0.1312,
        0.7137])

In [37]:
print(f'Max {tensor.max()}')
print(f'Min {tensor.min()}')
print(f'Type {tensor.type()}')


Max 0.9609602689743042
Min 0.13122117519378662
Type torch.FloatTensor


In [38]:
## Agrmax Operation

tensor.argmax()

tensor(3)

.argmax() function returns index of max value in tensor

## Playing with Shapes

In [39]:
x = torch.rand(size=(10,))
x

tensor([0.4763, 0.0808, 0.0935, 0.8473, 0.0669, 0.4493, 0.9190, 0.9290, 0.8700,
        0.8957])

In [40]:
# Reshape tensor

x_reshaped = x.reshape(2,5)
x_reshaped

tensor([[0.4763, 0.0808, 0.0935, 0.8473, 0.0669],
        [0.4493, 0.9190, 0.9290, 0.8700, 0.8957]])

In [41]:
# Stack the tensors

x_stacked = torch.stack([x,x,x])
x_stacked

tensor([[0.4763, 0.0808, 0.0935, 0.8473, 0.0669, 0.4493, 0.9190, 0.9290, 0.8700,
         0.8957],
        [0.4763, 0.0808, 0.0935, 0.8473, 0.0669, 0.4493, 0.9190, 0.9290, 0.8700,
         0.8957],
        [0.4763, 0.0808, 0.0935, 0.8473, 0.0669, 0.4493, 0.9190, 0.9290, 0.8700,
         0.8957]])

In [42]:
x_stacked.shape

torch.Size([3, 10])

In [43]:
# Squeeze for removing extra dimension from tensor

y = torch.rand(size=(1,5))
print(f'Tensor: {y}')
print(f'Tensor Shape: {y.shape}')

Tensor: tensor([[0.1326, 0.6030, 0.0122, 0.5864, 0.4100]])
Tensor Shape: torch.Size([1, 5])


In [44]:
# after squeezing

y_sq = y.squeeze()

print(f'Tensor: {y_sq}')
print(f'Tensor Shape: {y_sq.shape}')

Tensor: tensor([0.1326, 0.6030, 0.0122, 0.5864, 0.4100])
Tensor Shape: torch.Size([5])


## Indexing

In [45]:
arr =  torch.rand(size=(10,))
arr

tensor([0.8822, 0.0572, 0.6705, 0.1751, 0.4057, 0.7120, 0.4366, 0.9304, 0.6242,
        0.4766])

In [46]:
# First element
arr[0]

tensor(0.8822)

In [47]:
# start from 0 to 4
arr[:5]

tensor([0.8822, 0.0572, 0.6705, 0.1751, 0.4057])

In [48]:
# For last element
arr[-1]

tensor(0.4766)

In [49]:
mat = torch.rand(size=(10,5))
mat.shape

torch.Size([10, 5])

In [50]:
mat

tensor([[0.9126, 0.0262, 0.3753, 0.5627, 0.6249],
        [0.0412, 0.5366, 0.3683, 0.7437, 0.1137],
        [0.7517, 0.4699, 0.2195, 0.5195, 0.9021],
        [0.7996, 0.6750, 0.6937, 0.1434, 0.5945],
        [0.9224, 0.6254, 0.4342, 0.4762, 0.6709],
        [0.2296, 0.3339, 0.5948, 0.5295, 0.4331],
        [0.1911, 0.0979, 0.2716, 0.6519, 0.6312],
        [0.5298, 0.2288, 0.0638, 0.5603, 0.4560],
        [0.1859, 0.6622, 0.7094, 0.9196, 0.9933],
        [0.8544, 0.4521, 0.5720, 0.3376, 0.3500]])

In [51]:
# Row 1 and col 2
mat[1,2]

tensor(0.3683)

In [52]:
# all element of column 1
mat[:,1]

tensor([0.0262, 0.5366, 0.4699, 0.6750, 0.6254, 0.3339, 0.0979, 0.2288, 0.6622,
        0.4521])

In [53]:
# row 1 and all elements of col
mat[1,:]

tensor([0.0412, 0.5366, 0.3683, 0.7437, 0.1137])

## Convert Torch Tensor to Numpy

In [54]:
mat = torch.rand(size=(2,5))
mat

tensor([[7.8921e-02, 4.7682e-01, 8.4728e-01, 2.2645e-01, 7.5891e-01],
        [2.1035e-01, 3.0517e-01, 8.9538e-01, 5.6117e-01, 6.9231e-04]])

In [55]:
np_mat = mat.numpy()

In [56]:
np_mat

array([[7.8920782e-02, 4.7682387e-01, 8.4728372e-01, 2.2645146e-01,
        7.5890535e-01],
       [2.1034813e-01, 3.0516952e-01, 8.9538395e-01, 5.6117195e-01,
        6.9230795e-04]], dtype=float32)

### Check GPU in your machine

In [57]:
!nvidia-smi

Tue Dec  6 17:11:10 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 496.49       Driver Version: 496.49       CUDA Version: 11.5     |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ... WDDM  | 00000000:01:00.0  On |                  N/A |
| 31%   33C    P8    10W / 100W |   1071MiB /  4096MiB |     25%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------